import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";

export const ibmPlexBold = IBM_Plex_Sans_Arabic({
  variable: "--font-ibm-plex-bold",
  weight: "700"
});

export const ibmPlex = IBM_Plex_Sans_Arabic({
  variable: "--font-ibm-plex",
  subsets: ["latin"],
  weight: "300"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexBold.variable} ${ibmPlex.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
